### ISSUE TITLE
Module missing, production build errors out

### ISSUE THREAD

**Issue by Embiggenerd** [Lambda-School-Labs/budget-blocks-fe#104]
Automatic deploy for AWS amplify failed becuase of error:
    Error: [BABEL] /codebuild/output/src991677271/src/budget-blocks-fe/src/index.js: Cannot find module '@babel/plugin-syntax-top-level-await' (While processing: "/codebuild/output/src991677271/src/budget-blocks-fe/node_modules/babel-preset-react-app/index.js")

**Comment by debauchery1st** [comment]
https://babeljs.io/blog/2019/11/05/7.7.0#top-level-await-parsing-10449

**Comment by debauchery1st** [comment]
fixed with [this commit](https://github.com/Lambda-School-Labs/budget-blocks-fe/pull/108/commits/fbe4414bf8c417e5dbed771a56de87529421a332) ?
