### ISSUE TITLE
Stuck on onboarding page after manually creating a budget block

### ISSUE THREAD

**Issue by israelgonzalezb** [Lambda-School-Labs/budget-blocks-fe#84]
The app has me stuck on the route "/onBoard/1" after I manually created budget block. The continue button on the budget block creation screen redirects me to the onboarding page.

<img width="978" alt="Screen Shot 2020-03-11 at 10 02 32 AM" src="https://user-images.githubusercontent.com/48233351/76443360-874a2080-637f-11ea-8de6-7b7c6b100e97.png">

**Comment by maggieprice** [comment]
On the component BudgetGoalModal.jsx, the return is empty in MapStateToProps

**Comment by maggieprice** [comment]
There are 2 identically named components in separate folders. May be improperly referenced somewhere.

**Comment by maggieprice** [comment]
It looks this like it is only referenced once and that happens in App.js. It also is the proper component. Therefore, components/FirstOnboard can be deleted (I believe).

**Comment by maggieprice** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix redirect for block creation](https://trello.com/c/MpoSjhJw/87-fix-redirect-for-block-creation)

**Comment by israelgonzalezb** [comment]
@maggieprice 
Awesome job on this. I appreciate the details on what work you're doing to fix it.

Is this issue still open?
