### ISSUE TITLE
Sign-in button text disappears if backend times out

### ISSUE THREAD

**Issue by israelgonzalezb** [Lambda-School-Labs/budget-blocks-fe#94]
I tried signing in with a valid account. It looks like the Heroku backend didn't respond in time, probably because it had to wake up. Since it didn't respond in time, the sign-in button text disappeared. It seems like the button is still clickable, though.

<img width="788" alt="Screen Shot 2020-03-24 at 8 53 34 AM" src="https://user-images.githubusercontent.com/48233351/77447717-3853b080-6dad-11ea-977e-c9736b218d95.png">

**Comment by israelgonzalezb** [comment]
Console errors attached

<img width="541" alt="Screen Shot 2020-03-24 at 8 56 46 AM" src="https://user-images.githubusercontent.com/48233351/77447897-6e913000-6dad-11ea-9e77-9b59a89ffe6e.png">

**Comment by Edwin-Chajon** [comment]
<img width="796" alt="Screen Shot 2020-04-13 at 1 49 53 PM" src="https://user-images.githubusercontent.com/53211523/79160072-0de28b00-7d8e-11ea-84af-cd58edcbb629.png">
<img width="785" alt="Screen Shot 2020-04-13 at 1 52 35 PM" src="https://user-images.githubusercontent.com/53211523/79160081-11761200-7d8e-11ea-8483-1d570c2af47a.png">

cannot replicate error after several attempts across other devices and browsers.
