### ISSUE TITLE
Sign out link persists even if user is not logged in

### ISSUE THREAD

**Issue by israelgonzalezb** [Lambda-School-Labs/budget-blocks-fe#97]
It seems like a sign out link sticks around even if a user is not logged in....

**Comment by israelgonzalezb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RC2 Product Cycle Completion Status](https://trello.com/c/TYpe6lTa/54-rc2-product-cycle-completion-status)

**Comment by debauchery1st** [comment]
[NavBar.js](https://github.com/Lambda-School-Labs/budget-blocks-fe/blob/development/src/components/NavBar.js)

**Comment by israelgonzalezb** [comment]
In the code below, the check for `navState === ""` causes the log out link to persist. If the user is not logged in, navState gets set to "undefined" which causes the condition to fail. We might be able to fix this by just checking for truthiness for now...

```
export function NavBar({ navState, logoutUser }) {
  return (
    <div className="nav-bar">
      <div className="nav-logo">
        <img className="image" src={logo} />
        <img className="heading" src={head} />
      </div>
      <div className="nav-action">
        {navState === "" ? (
          ""
        ) : (
          <Link onClick={logoutUser} to="/login"> {/* We could use display:none with a a ternary */}
            Log Out
          </Link>
        )}
      </div>
    </div>
  );
}
```

**Comment by israelgonzalezb** [comment]
When you first register, the app redirects you to /onboard/1. If you abandon the onboarding, and go back to the root, you will see the log out button, even though you're technically not logged in.

**Comment by israelgonzalezb** [comment]
An unauthenticated user can still access /onboard/1. For example, /dashboard redirects us to /login if the user is not logged in. We need to do the same on /onboard/1.
